### ISSUE TITLE
http://www.snik.eu/ontology/it4it/FunctionalComponent v0.3.3, 2017-04-18

### ISSUE THREAD

**Issue by KonradHoeffner** [snikproject/ontology#100]
The class http://www.snik.eu/ontology/it4it/FunctionalComponent doesn't have a sub top class, so I assign it to EntityType. Find out if there is a more fitting solution to integrate it with the SNIK meta model.

**Comment by KonradHoeffner** [comment]
There seem to be more of that kind, please investigate.

**Comment by SebStaeubert** [comment]
According to this definition http://pubs.opengroup.org/it4it/refarch20/m/chap02.html
FunctionalComponent corresponds closer to Computerbased Application Component.

**Comment by KonradHoeffner** [comment]
Which relation should we use between them, rdfs:subClassOf?

**Comment by KonradHoeffner** [comment]
@SebStaeubert:
I move the issue to the next milestone because it seems IT4IT is not heavily maintained at the moment.
meta:functionComponent represents a part-of relation (Teil-Ganzes Beziehung). For example, :car meta:carComponent :wheel.
