### ISSUE TITLE
ob:InformationManagement skos:closeMatch bb:InformationManagement v2018-10-22

### ISSUE THREAD

**Issue by AlfredWinter** [snikproject/ontology#189]
The edge "ob:InformationManagement skos:closeMatch bb:InformationManagement" is incorrect.

**Details**
Beziehung muss gelöscht werden. information management Function ist eine art Meta-Konzept.

**Comment by AlfredWinter** [comment]
ACHTUNG ZURÜCK!!!!!
da steckt irgendwo ein Fehler. Es wird offenbar nicht zwischen bb:Informationsmanagement und Informationsmanagementfunction unterschieden

**Comment by KonradHoeffner** [comment]
bb:InformationManagement ist momentan eine Sammelklasse, die wieder aufgeteilt werden soll (siehe Issue #190. Dadurch ist bb:InformationManagement momentan kein valider closeMatch zu ob:InformationManagement. Aber noch nicht löschen, sondern nach Durchführung von #190 prüfen, dass diese Kante nicht verloren gegangen ist. Es darf danach kein close match zwischen bb:InformationManagementFunction und obInformationManagement bestehen.

**Comment by KonradHoeffner** [comment]
Da Anna nicht mehr da ist, weise ich das mal @FranziskaJahn und @BirgitSNIK zu. Bitte sagt Bescheid, wie es hier weitergehen soll.

**Comment by KonradHoeffner** [comment]
Zwei Jahre später scheint ich das Problem nicht mehr vorhanden zu sein.
bb:InformationManagement ist eine Aufgabe und hat auch nur nach dem Metamodell für Aufgaben valide Beziehungen der Form functionComponent und uses. bb:InformationManagementFunction gibt es nicht mehr.

Daher betrachte ich die Issue als erledigt, falls das jemand anders sieht bitte wieder öffnen.
