### ISSUE TITLE
Relation "isResponsibleForRole" einführen?

### ISSUE THREAD

**Issue by AnnaLoerke** [snikproject/ontology#196]
Aktuell gibt es die Relation "CIO"(Rolle) "isResponsibleForFunction" "DepartmentOfInformationManagement"(Funktion). Allerdings soll die Funktion in eine Rolle umgewandelt werden. Dabei würde jedoch nur "roleComponent" als Relation möglich sein und die Hierarchie-Beziehung ginge verloren. Ticket #194 beschreibt ein ähnliches Problem.

Birgit und ich würden gerne im Team diskutieren, ob eine Erweiterung des Meta-Modells bezüglich "isResponsibleForRole" sinnvoll wäre.

**Comment by KonradHoeffner** [comment]
Konrad: Add to meta model.
Franziska: Add definition.
Anna/Ludwig: Use roleComponent in new connections and when remoddeling others to roles.
Also go through all connections of roles to roles using meta:roleComponent or rdfs:subClassOf and check, if they should be meta:isResponsibleForRole instead and remodel if that is the case.

There are 50 subclasses and 15 role components:

select count(distinct(?r))
{
 ?r meta:subTopClass meta:Role.
 ?s meta:subTopClass meta:Role.
 {?r meta:roleComponent ?s.} UNION {?r rdfs:subClassOf ?s.}
}

**Comment by KonradHoeffner** [comment]
```
SELECT DISTINCT ?r ?p ?s
{
 ?r meta:subTopClass meta:Role.
 ?s meta:subTopClass meta:Role.
 ?r ?p ?s.
 FILTER(?p=meta:roleComponent||?p=rdfs:subClassOf)
}
```
Please investigate and enter your decision into <https://docs.google.com/spreadsheets/d/1nxSu8pkYAJPK4JgQ_WYXucMs-Q6xTD3AXS4d9fp_a8M>.

r | p | s
-- | -- | --
http://www.snik.eu/ontology/bb/Surgeon | http://www.w3.org/2000/01/rdf-schema#subClassOf | http://www.snik.eu/ontology/bb/Physician
http://www.snik.eu/ontology/ciox/StakeholderPatientenversorgung | http://www.w3.org/2000/01/rdf-schema#subClassOf | http://www.snik.eu/ontology/ciox/ItStrategieStakeholder
http://www.snik.eu/ontology/ciox/StakeholderForschungUndLehre | http://www.w3.org/2000/01/rdf-schema#subClassOf | http://www.snik.eu/ontology/ciox/ItStrategieStakeholder
http://www.snik.eu/ontology/ciox/StakeholderInformationsmanagement | http://www.w3.org/2000/01/rdf-schema#subClassOf | http://www.snik.eu/ontology/ciox/ItStrategieStakeholder
http://www.snik.eu/ontology/he/AdministrativeManagementebene | http://www.w3.org/2000/01/rdf-schema#subClassOf | http://www.snik.eu/ontology/he/Managementebene(Personen)
http://www.snik.eu/ontology/he/Anwendungsadministrator | http://www.w3.org/2000/01/rdf-schema#subClassOf | http://www.snik.eu/ontology/he/Stelle
http://www.snik.eu/ontology/bb/Physician | http://www.w3.org/2000/01/rdf-schema#subClassOf | http://www.snik.eu/ontology/bb/HealthCareProfessional
http://www.snik.eu/ontology/bb/Nurse | http://www.w3.org/2000/01/rdf-schema#subClassOf | http://www.snik.eu/ontology/bb/HealthCareProfessional
http://www.snik.eu/ontology/bb/TopManagement | http://www.w3.org/2000/01/rdf-schema#subClassOf | http://www.snik.eu/ontology/bb/HospitalStaff
http://www.snik.eu/ontology/bb/ChiefExecutiveOfficer | http://www.w3.org/2000/01/rdf-schema#subClassOf | http://www.snik.eu/ontology/bb/HospitalStaff
http://www.snik.eu/ontology/bb/ChiefFinancialOfficer | http://www.w3.org/2000/01/rdf-schema#subClassOf | http://www.snik.eu/ontology/bb/HospitalStaff
http://www.snik.eu/ontology/bb/ItServiceManagementStaff | http://www.w3.org/2000/01/rdf-schema#subClassOf | http://www.snik.eu/ontology/bb/InformationManagementStaff
http://www.snik.eu/ontology/ciox/Projektauftraggeber | http://www.w3.org/2000/01/rdf-schema#subClassOf | http://www.snik.eu/ontology/ciox/HISStakeholder
http://www.snik.eu/ontology/ciox/Wartungsfensterkoordinator | http://www.w3.org/2000/01/rdf-schema#subClassOf | http://www.snik.eu/ontology/ciox/InformationManagementStaff
http://www.snik.eu/ontology/ciox/Abteilungsleiter | http://www.w3.org/2000/01/rdf-schema#subClassOf | http://www.snik.eu/ontology/ciox/InformationManagementStaff
http://www.snik.eu/ontology/ciox/Projektleiter | http://www.w3.org/2000/01/rdf-schema#subClassOf | http://www.snik.eu/ontology/ciox/InformationManagementStaff
http://www.snik.eu/ontology/ciox/Bereichsassistenz | http://www.w3.org/2000/01/rdf-schema#subClassOf | http://www.snik.eu/ontology/ciox/InformationManagementStaff
http://www.snik.eu/ontology/he/DatenmanagementalsLinienabteilung | http://www.w3.org/2000/01/rdf-schema#subClassOf | http://www.snik.eu/ontology/he/Abteilung
http://www.snik.eu/ontology/he/DatenmanagementalsStellederItAbteilung | http://www.w3.org/2000/01/rdf-schema#subClassOf | http://www.snik.eu/ontology/he/Abteilung
http://www.snik.eu/ontology/he/Finanzabteilung | http://www.w3.org/2000/01/rdf-schema#subClassOf | http://www.snik.eu/ontology/he/Abteilung
http://www.snik.eu/ontology/he/ItAbteilung | http://www.w3.org/2000/01/rdf-schema#subClassOf | http://www.snik.eu/ontology/he/Abteilung
http://www.snik.eu/ontology/he/Stabsstelle | http://www.w3.org/2000/01/rdf-schema#subClassOf | http://www.snik.eu/ontology/he/Abteilung
http://www.snik.eu/ontology/he/Linienstelle | http://www.w3.org/2000/01/rdf-schema#subClassOf | http://www.snik.eu/ontology/he/ControllingStelle
http://www.snik.eu/ontology/he/OperativeManagementebene | http://www.w3.org/2000/01/rdf-schema#subClassOf | http://www.snik.eu/ontology/he/Managementebene(Personen)
http://www.snik.eu/ontology/he/ControllingStelle | http://www.w3.org/2000/01/rdf-schema#subClassOf | http://www.snik.eu/ontology/he/Stabsstelle
http://www.snik.eu/ontology/he/DatenmanagementalsStabsstellederUnternehmensleitung | http://www.w3.org/2000/01/rdf-schema#subClassOf | http://www.snik.eu/ontology/he/Stabsstelle
http://www.snik.eu/ontology/he/CallCenterManager | http://www.w3.org/2000/01/rdf-schema#subClassOf | http://www.snik.eu/ontology/he/Stelle
http://www.snik.eu/ontology/he/ChiefExecutiveOfficer | http://www.w3.org/2000/01/rdf-schema#subClassOf | http://www.snik.eu/ontology/he/Stelle
http://www.snik.eu/ontology/he/ChiefFinancialOfficer | http://www.w3.org/2000/01/rdf-schema#subClassOf | http://www.snik.eu/ontology/he/Stelle
http://www.snik.eu/ontology/he/ChiefInformationOfficer | http://www.w3.org/2000/01/rdf-schema#subClassOf | http://www.snik.eu/ontology/he/Stelle
http://www.snik.eu/ontology/he/ChiefKnowledgeOfficer | http://www.w3.org/2000/01/rdf-schema#subClassOf | http://www.snik.eu/ontology/he/Stelle
http://www.snik.eu/ontology/he/Controller | http://www.w3.org/2000/01/rdf-schema#subClassOf | http://www.snik.eu/ontology/he/Stelle
http://www.snik.eu/ontology/he/ControllingStelle | http://www.w3.org/2000/01/rdf-schema#subClassOf | http://www.snik.eu/ontology/he/Stelle
http://www.snik.eu/ontology/he/CorporateInformationSecurityOfficer | http://www.w3.org/2000/01/rdf-schema#subClassOf | http://www.snik.eu/ontology/he/Stelle
http://www.snik.eu/ontology/he/Datenbankdesigner | http://www.w3.org/2000/01/rdf-schema#subClassOf | http://www.snik.eu/ontology/he/Stelle
http://www.snik.eu/ontology/he/Entwicklungsadministrator | http://www.w3.org/2000/01/rdf-schema#subClassOf | http://www.snik.eu/ontology/he/Stelle
http://www.snik.eu/ontology/he/Informationsmanager | http://www.w3.org/2000/01/rdf-schema#subClassOf | http://www.snik.eu/ontology/he/Stelle
http://www.snik.eu/ontology/he/ItArchitekt | http://www.w3.org/2000/01/rdf-schema#subClassOf | http://www.snik.eu/ontology/he/Stelle
http://www.snik.eu/ontology/he/ItController | http://www.w3.org/2000/01/rdf-schema#subClassOf | http://www.snik.eu/ontology/he/Stelle
http://www.snik.eu/ontology/he/ItManager | http://www.w3.org/2000/01/rdf-schema#subClassOf | http://www.snik.eu/ontology/he/Stelle
http://www.snik.eu/ontology/he/ItRevisor | http://www.w3.org/2000/01/rdf-schema#subClassOf | http://www.snik.eu/ontology/he/Stelle
http://www.snik.eu/ontology/he/Organisator | http://www.w3.org/2000/01/rdf-schema#subClassOf | http://www.snik.eu/ontology/he/Stelle
http://www.snik.eu/ontology/he/Problemkoordinator | http://www.w3.org/2000/01/rdf-schema#subClassOf | http://www.snik.eu/ontology/he/Stelle
http://www.snik.eu/ontology/he/Produktionsmanager | http://www.w3.org/2000/01/rdf-schema#subClassOf | http://www.snik.eu/ontology/he/Stelle
http://www.snik.eu/ontology/he/Produktmanager | http://www.w3.org/2000/01/rdf-schema#subClassOf | http://www.snik.eu/ontology/he/Stelle
http://www.snik.eu/ontology/he/Projektmanager | http://www.w3.org/2000/01/rdf-schema#subClassOf | http://www.snik.eu/ontology/he/Stelle
http://www.snik.eu/ontology/he/Rechenzentrumsleiter | http://www.w3.org/2000/01/rdf-schema#subClassOf | http://www.snik.eu/ontology/he/Stelle
http://www.snik.eu/ontology/he/Revisor | http://www.w3.org/2000/01/rdf-schema#subClassOf | http://www.snik.eu/ontology/he/Stelle
http://www.snik.eu/ontology/he/RolloutManager | http://www.w3.org/2000/01/rdf-schema#subClassOf | http://www.snik.eu/ontology/he/Stelle
http://www.snik.eu/ontology/he/Sicherheitsbeauftragter | http://www.w3.org/2000/01/rdf-schema#subClassOf | http://www.snik.eu/ontology/he/Stelle
http://www.snik.eu/ontology/he/Softwareentwickler | http://www.w3.org/2000/01/rdf-schema#subClassOf | http://www.snik.eu/ontology/he/Stelle
http://www.snik.eu/ontology/bb/HardwareVendor | http://www.w3.org/2000/01/rdf-schema#subClassOf | http://www.snik.eu/ontology/bb/Vendor
http://www.snik.eu/ontology/bb/HospitalStaff | http://www.w3.org/2000/01/rdf-schema#subClassOf | http://www.snik.eu/ontology/bb/HisStakeholder
http://www.snik.eu/ontology/he/StrategischeManagementebene | http://www.w3.org/2000/01/rdf-schema#subClassOf | http://www.snik.eu/ontology/he/Managementebene(Personen)
http://www.snik.eu/ontology/bb/DataSecurityOfficer | http://www.w3.org/2000/01/rdf-schema#subClassOf | http://www.snik.eu/ontology/bb/HospitalStaff
http://www.snik.eu/ontology/bb/InformationManagementStaff | http://www.w3.org/2000/01/rdf-schema#subClassOf | http://www.snik.eu/ontology/bb/HospitalStaff
http://www.snik.eu/ontology/bb/AdministrativeStaff | http://www.w3.org/2000/01/rdf-schema#subClassOf | http://www.snik.eu/ontology/bb/HospitalStaff
http://www.snik.eu/ontology/bb/DepartmentalSystemAdministrator | http://www.w3.org/2000/01/rdf-schema#subClassOf | http://www.snik.eu/ontology/bb/HospitalStaff
http://www.snik.eu/ontology/bb/HospitalsBoardOfDirectors | http://www.w3.org/2000/01/rdf-schema#subClassOf | http://www.snik.eu/ontology/bb/HospitalStaff
http://www.snik.eu/ontology/bb/HealthCareProfessional | http://www.w3.org/2000/01/rdf-schema#subClassOf | http://www.snik.eu/ontology/bb/HospitalStaff
http://www.snik.eu/ontology/bb/ComputingCenterManager | http://www.w3.org/2000/01/rdf-schema#subClassOf | http://www.snik.eu/ontology/bb/InformationManagementStaff
http://www.snik.eu/ontology/bb/ProjectManager | http://www.w3.org/2000/01/rdf-schema#subClassOf | http://www.snik.eu/ontology/bb/InformationManagementStaff
http://www.snik.eu/ontology/bb/OperationalInformationManagementStaff | http://www.w3.org/2000/01/rdf-schema#subClassOf | http://www.snik.eu/ontology/bb/InformationManagementStaff
http://www.snik.eu/ontology/bb/ChiefInformationOfficer | http://www.w3.org/2000/01/rdf-schema#subClassOf | http://www.snik.eu/ontology/bb/InformationManagementStaff
http://www.snik.eu/ontology/bb/MedicalInformatician | http://www.w3.org/2000/01/rdf-schema#subClassOf | http://www.snik.eu/ontology/bb/InformationManagementStaff
http://www.snik.eu/ontology/ob/SpecificationTeam | http://www.snik.eu/ontology/meta/roleComponent | http://www.snik.eu/ontology/ob/DomainExpert
http://www.snik.eu/ontology/ob/ProjectTeam | http://www.snik.eu/ontology/meta/roleComponent | http://www.snik.eu/ontology/ob/ProjectTeamMember
http://www.snik.eu/ontology/ob/SpecificationTeam | http://www.snik.eu/ontology/meta/roleComponent | http://www.snik.eu/ontology/ob/ProjectTeamMember
http://www.snik.eu/ontology/bb/TopManagement | http://www.snik.eu/ontology/meta/roleComponent | http://www.snik.eu/ontology/bb/ChiefExecutiveOfficer
http://www.snik.eu/ontology/bb/HospitalsBoardOfDirectors | http://www.snik.eu/ontology/meta/roleComponent | http://www.snik.eu/ontology/bb/ChiefExecutiveOfficer
http://www.snik.eu/ontology/bb/InformationManagementBoard | http://www.snik.eu/ontology/meta/roleComponent | http://www.snik.eu/ontology/bb/ChiefExecutiveOfficer
http://www.snik.eu/ontology/bb/ProjectManagementBoard | http://www.snik.eu/ontology/meta/roleComponent | http://www.snik.eu/ontology/bb/TopManagement
http://www.snik.eu/ontology/bb/TopManagement | http://www.snik.eu/ontology/meta/roleComponent | http://www.snik.eu/ontology/bb/ChiefFinancialOfficer
http://www.snik.eu/ontology/bb/HospitalsBoardOfDirectors | http://www.snik.eu/ontology/meta/roleComponent | http://www.snik.eu/ontology/bb/ChiefFinancialOfficer
http://www.snik.eu/ontology/bb/SeniorPhysician | http://www.w3.org/2000/01/rdf-schema#subClassOf | http://www.snik.eu/ontology/bb/Physician
http://www.snik.eu/ontology/bb/WardPhysician | http://www.w3.org/2000/01/rdf-schema#subClassOf | http://www.snik.eu/ontology/bb/Physician
http://www.snik.eu/ontology/bb/ProjectManagementBoard | http://www.snik.eu/ontology/meta/roleComponent | http://www.snik.eu/ontology/bb/Vendor
http://www.snik.eu/ontology/bb/SoftwareVendor | http://www.w3.org/2000/01/rdf-schema#subClassOf | http://www.snik.eu/ontology/bb/Vendor
http://www.snik.eu/ontology/ob/HumanActor | http://www.w3.org/2000/01/rdf-schema#subClassOf | http://www.snik.eu/ontology/ob/Actor
http://www.snik.eu/ontology/ob/SpecificationTeam | http://www.snik.eu/ontology/meta/roleComponent | http://www.snik.eu/ontology/ob/Sponsor
http://www.snik.eu/ontology/ob/SpecificationTeam | http://www.snik.eu/ontology/meta/roleComponent | http://www.snik.eu/ontology/ob/User
http://www.snik.eu/ontology/ciox/AbteilungsleiterApplikationsmanagement | http://www.w3.org/2000/01/rdf-schema#subClassOf | http://www.snik.eu/ontology/ciox/Abteilungsleiter
http://www.snik.eu/ontology/ciox/AbteilungsleiterProjektUndProzessmanagement | http://www.w3.org/2000/01/rdf-schema#subClassOf | http://www.snik.eu/ontology/ciox/Abteilungsleiter
http://www.snik.eu/ontology/ciox/ChangeAdvisoryBoard | http://www.snik.eu/ontology/meta/roleComponent | http://www.snik.eu/ontology/ciox/Abteilungsleiter
http://www.snik.eu/ontology/ciox/DepartmentManagerSystemManagement | http://www.w3.org/2000/01/rdf-schema#subClassOf | http://www.snik.eu/ontology/ciox/Abteilungsleiter
http://www.snik.eu/ontology/ciox/ChangeAdvisoryBoard | http://www.snik.eu/ontology/meta/roleComponent | http://www.snik.eu/ontology/ciox/Bereichsassistenz
http://www.snik.eu/ontology/bb/InformationManagementBoard | http://www.snik.eu/ontology/meta/roleComponent | http://www.snik.eu/ontology/bb/HisStakeholder
http://www.snik.eu/ontology/ciox/Lenkungsausschuss | http://www.snik.eu/ontology/meta/roleComponent | http://www.snik.eu/ontology/ciox/ItStrategieStakeholder
http://www.snik.eu/ontology/he/TopManagement | http://www.snik.eu/ontology/meta/roleComponent | http://www.snik.eu/ontology/he/ChiefInformationOfficer
http://www.snik.eu/ontology/he/ItLenkungsausschuss | http://www.snik.eu/ontology/meta/roleComponent | http://www.snik.eu/ontology/he/Fachbereich
http://www.snik.eu/ontology/he/LowerManagement | http://www.snik.eu/ontology/meta/roleComponent | http://www.snik.eu/ontology/he/HelpdeskManager
http://www.snik.eu/ontology/he/ItLenkungsausschuss | http://www.snik.eu/ontology/meta/roleComponent | http://www.snik.eu/ontology/he/ItAbteilung
http://www.snik.eu/ontology/he/ItAbteilung | http://www.snik.eu/ontology/meta/roleComponent | http://www.snik.eu/ontology/he/ItAbteilungEntwicklung
http://www.snik.eu/ontology/he/ItAbteilung | http://www.snik.eu/ontology/meta/roleComponent | http://www.snik.eu/ontology/he/ItAbteilungHelpdesk
http://www.snik.eu/ontology/he/ItAbteilung | http://www.snik.eu/ontology/meta/roleComponent | http://www.snik.eu/ontology/he/ItAbteilungLeitung
http://www.snik.eu/ontology/he/ItAbteilung | http://www.snik.eu/ontology/meta/roleComponent | http://www.snik.eu/ontology/he/ItAbteilungProduktion
http://www.snik.eu/ontology/he/TopManagement | http://www.snik.eu/ontology/meta/roleComponent | http://www.snik.eu/ontology/he/Lenkungsausschuss
http://www.snik.eu/ontology/he/LowerManagement | http://www.snik.eu/ontology/meta/roleComponent | http://www.snik.eu/ontology/he/Operator
http://www.snik.eu/ontology/he/QFDTeam | http://www.snik.eu/ontology/meta/roleComponent | http://www.snik.eu/ontology/he/Produktmanager
http://www.snik.eu/ontology/he/Abteilung | http://www.snik.eu/ontology/meta/roleComponent | http://www.snik.eu/ontology/he/Stelle
http://www.snik.eu/ontology/he/ItManager | http://www.snik.eu/ontology/meta/roleComponent | http://www.snik.eu/ontology/he/Technologiemanager
http://www.snik.eu/ontology/he/Linienmanagement | http://www.snik.eu/ontology/meta/roleComponent | http://www.snik.eu/ontology/he/Technologiemanager
http://www.snik.eu/ontology/bb/InformationManagementBoard | http://www.snik.eu/ontology/meta/roleComponent | http://www.snik.eu/ontology/bb/ChiefInformationOfficer
http://www.snik.eu/ontology/bb/RepresentativeOfHospitalDepartment | http://www.w3.org/2000/01/rdf-schema#subClassOf | http://www.snik.eu/ontology/bb/HospitalStaff
http://www.snik.eu/ontology/bb/ServiceDeskStaff | http://www.w3.org/2000/01/rdf-schema#subClassOf | http://www.snik.eu/ontology/bb/InformationManagementStaff
http://www.snik.eu/ontology/bb/ProjectManagementBoard | http://www.snik.eu/ontology/meta/roleComponent | http://www.snik.eu/ontology/bb/ProjectManager
http://www.snik.eu/ontology/bb/ProjectManagementBoard | http://www.snik.eu/ontology/meta/roleComponent | http://www.snik.eu/ontology/bb/RepresentativeOfHospitalDepartment
http://www.snik.eu/ontology/ob/ProjectTeam | http://www.snik.eu/ontology/meta/roleComponent | http://www.snik.eu/ontology/ob/ProjectManager
http://www.snik.eu/ontology/ciox/ChangeAdvisoryBoard | http://www.snik.eu/ontology/meta/roleComponent | http://www.snik.eu/ontology/ciox/ChiefInformationOfficer
http://www.snik.eu/ontology/ciox/ChiefExecutiveOfficer | http://www.w3.org/2000/01/rdf-schema#subClassOf | http://www.snik.eu/ontology/ciox/HISStakeholder
http://www.snik.eu/ontology/ciox/HospitalStaff | http://www.w3.org/2000/01/rdf-schema#subClassOf | http://www.snik.eu/ontology/ciox/HISStakeholder
http://www.snik.eu/ontology/ciox/InformationManagementStaff | http://www.w3.org/2000/01/rdf-schema#subClassOf | http://www.snik.eu/ontology/ciox/HospitalStaff
http://www.snik.eu/ontology/ciox/ChangeAdvisoryBoard | http://www.w3.org/2000/01/rdf-schema#subClassOf | http://www.snik.eu/ontology/ciox/InformationManagementStaff
http://www.snik.eu/ontology/ciox/ChiefInformationOfficer | http://www.w3.org/2000/01/rdf-schema#subClassOf | http://www.snik.eu/ontology/ciox/InformationManagementStaff
http://www.snik.eu/ontology/ciox/MitarbeiterVertragsmanagement | http://www.w3.org/2000/01/rdf-schema#subClassOf | http://www.snik.eu/ontology/ciox/InformationManagementStaff

**Comment by KonradHoeffner** [comment]
Da diese Issue seit fast 3 Jahren offen ist, habe ich mich jetzt selbst durch die 115 Einträge der Tabelle gewühlt und habe dabei keinen Kandidaten für eine Umänderung auf isResponsibleForRole gefunden.
Falls eine der Domänenexpertinnen das anders sieht, Issue bitte wieder öffnen, aber ich behandle das jetzt als erledigt.
