### ISSUE TITLE
Conflicting values for consolidated

### ISSUE THREAD

**Issue by KonradHoeffner** [snikproject/ontology#226]
For example, http://www.snik.eu/ontology/he/StrategischeSchlagkraft has meta:consolidated 0 *and* 1 as values. Drop the zero and go with the one in those cases?

**Comment by KonradHoeffner** [comment]
g | no | yes | both
-- | -- | -- | --
http://www.snik.eu/ontology/he | 1470 | 583 | 158

Created by

```
select *
{
 {
 select ?g count(?x) as ?no
 {
 graph ?g
 {
 ?x meta:consolidated "0"^^xsd:integer.
 }
 }
 }

 {
 select ?g count(?y) as ?yes
 {
 graph ?g
 {
 ?y meta:consolidated "1"^^xsd:integer.
 }}}

 {
 select ?g count(?z) as ?both
 {
 graph ?g
 {
 ?z meta:consolidated "1"^^xsd:integer.
 ?z meta:consolidated "0"^^xsd:integer.
 }}}

} group by ?g
```

**Comment by AlfredWinter** [comment]
Keep it like this to mark conflicting base information.
