### ISSUE TITLE
Domain und Range Verletzungen

### ISSUE THREAD

**Issue by KonradHoeffner** [snikproject/ontology#245]
Es gibt viele Tripel, bei denen Relationen zwischen Klassen benutzt werden, bei denen das gar nicht erlaubt ist nach dem Metamodell.

Diese können im Quality Checker gefunden werden unter:

- https://snikproject.github.io/ontology/2017/06/01/qualitycheck/#domain-violation
- https://snikproject.github.io/ontology/2017/06/01/qualitycheck/#range-violation

**Comment by AnnaLoerke** [comment]
@KonradHoeffner Wenn ich den Quality Check öffnen, zeigt er mir auch beim drauf klicken keine Tabelle an. Ich glaube da gab es irgendeinen Workaround, weißt du noch welchen?

**Comment by KonradHoeffner** [comment]
Klar, der Fehler kommt vom fehlenden https-Zertifikat für snik.eu (GLPI Tickets https://nikolaus.imise.uni-leipzig.de/glpi/front/ticket.form.php?id=13426 und https://nikolaus.imise.uni-leipzig.de/glpi/front/ticket.form.php?id=11202).

Der Workaround ist, auf https://www.snik.eu zu gehen und die https-Ausnahmeregel zu bestätigen.

**Comment by AnnaLoerke** [comment]
Nein, zumindest auf meinem Laptop nicht (weder Safari noch Google Chrome). Werde es dann nächste Woche mal im Büro probieren...

**Comment by KonradHoeffner** [comment]
Die Domain- und Range-Verletzungen bestehen immer noch. Da müssen die Expertinnen mal in Ruhe drübergucken und entscheiden. Es gab im Qualitycheck noch ein kleines Problem mit den Links aber das habe ich jetzt behoben (Update Sgvizler auf Version 0.7).

**Comment by KonradHoeffner** [comment]
Wir haben uns um ob:Vendor gekümmert und bb:Vendor, das ist erledigt. (SNIK Jour Fixe 2020-02-18) Der Rest muss noch erledigt werden.
