### ISSUE TITLE
2. SPARQL Endpunkt?

### ISSUE THREAD

**Issue by KonradHoeffner** [snikproject/ontology#253]
Da wir momentan viel ändern wäre es vielleicht gut, einen zweiten SPARQL Endpunkt zu haben, der nur unregelmäßig aktualisiert wird, damit man eine stabile Version für Evaluationen für Paper hat und als Notfallsystem für unsere Anwendungen. Außerdem kann das bei der Fehlersuche helfen, wenn man die aktuellen Daten mit den alten vergleichen kann. Was meinen die Anderen?

**Comment by AlfredWinter** [comment]
- Jeweils ein Release auf 2. SPARQL Endpunkt (Docker container) hochladen oder als graphen.
- Stabile Version für Paper
- überlegen wie das mit SNIK Graph

**Comment by SebStaeubert** [comment]
Das ist möglich, d.h. ich könnte einen weiteren Virtuoso Container starten. Müssen weitere Container vorhanden sein, z.B. um die komplette SNIK Dienste zu duplizieren oder werden die bestehenden Dienste in der Art modifiziert, dass sie auf die verschiedenen SPARQL Endpunkte verzweigen?
Am Einfachsten ist vermutlich 2 komplette SNIK Umgebungen zu haben: "Dev" und "Prod", oder?

**Comment by KonradHoeffner** [comment]
Mir würde erstmal ein 2. Endpunkt, also zweiter Virtuoso-Container reichen ohne weitere Dienste zu duplizieren. Aber selbst das ist auch nicht so dringend, da wir ja auch RDF Dumps für die Paper hochladen können.

**Comment by KonradHoeffner** [comment]
Da wir momentan nur noch selten etwas ändern und unter <https://github.com/snikproject/docker> das Docker Setup haben, mit dem man einen lokalen SPARQL Endpunkt auch mit einem älteren Stand wiederherstellen kann, schätze ich das als nicht mehr nötig ein und schließe die Issue. Bitte wieder öffnen, wenn es doch benötigt wird.
