### ISSUE TITLE
http://www.snik.eu/ontology/bb/InternationalDICOMCommittee

### ISSUE THREAD

**Issue by AlfredWinter** [snikproject/ontology#258]
The class http://www.snik.eu/ontology/bb/InternationalDICOMCommittee has [incorrect/missing attribute values | incorrect/missing relations to other classes, other (please specify and remove not applicable ones).]

**Details**
Diese Klasse ist responsibleForEntityType für DicomStandard. Dann müsste sie aber eine Rolle sein. Sie ist aber subclass of Organization - auch keine Rolle sondern Entity Type. An Organization hängen auch wieder einige Entitytypes als subclasses dran - bis auf ein Rolle: Funding institution. Das muss alles aufgeräumt werden.

**Comment by AlfredWinter** [comment]
Ich sehe gerade, dass auch IHE subclass of Organization ist. wenn nun Organization zur Rolle würde, dann würde auch IHE zur Rolle und dann könnte man auch die beiden associatedWith, die von IHE ausgehen, präzisieren.

**Comment by LudwigWermke** [comment]
Wechseln von Organization zu Rolle würde folgenden Rattenschwanz nach sich ziehen (noch nicht fertig): 
**A) Ummodellieren von sämtlichen Subklassen:**

- **http://www.snik.eu/ontology/bb/EuroRec** (eine Institution, also eher Rolle; Änderunge zu Rolle würde falsche Relationen korrigieren (besitzt eine Relation, die von Rolle auf Function zeigt)

- **http://www.snik.eu/ontology/bb/Cchit** (eine non-profit-Organization; Änderung zu Rolle würde falsche Relationen korrigieren (besitzt eine Relation, die von Rolle auf Function zeigt)

- **http://www.snik.eu/ontology/bb/Ccow:** eine Arbeitsgruppe vmtl an einm Unterpunkt zu HL7; Die Beziehung "isAssociatedWith" (-> HL7-Spaß (Entity-Type)) kann evtl. Probleme verursachen, da sich mir aus dem Meta-model nicht erschließt, ob eine Beziehung isAssociatedWith zwischen "Role" und "Entity Type" erlaubt is

- **http://www.snik.eu/ontology/bb/Cen** - irgendein Kommittee; Änderung zu Rolle würde falsche Relationen korrigieren (besitzt eine Relation, die von Rolle auf Function zeigt)

- **http://www.snik.eu/ontology/bb/Ihe** - eine Organisation, definitiv falsch modelliert. Muss eine Rolle sein. Änderung kann Probleme verursachen: es existieren zwei Beziehungen "isAssociatedWith" zu einem "Entity Type" sowie eine Inverse Beziehung "isAssociatedWith" mit IHE Connect-a-thon (Entity Type)

- **http://www.snik.eu/ontology/bb/FundingInstitution** (laut BB (Strg+F) nur zweimal erwähnt und definitiv nur eine Aufgabe und daher falsch modelliert. Definitv keine Subklasse von Organization vmtl auch nicht von HIS Interessenvertreter; weitere Modellierungsprobleme bei den relationen zu anderen Klassen, die aber vertretba sind) Man müsse hier recherchieren, wo das alles neu eingehängt werden soll

- **http://www.snik.eu/ontology/bb/GovernmentalAuthority:** wird im bb nur in Nebensätzen erwähnt, Genaugenommen handelt es sich hier um die Regierung/den Teil der Exekutiven, der u.A. für Health-Care-Networks verantwortlich ist (dahe auch die Verbidnung zu Gesundheitsversorgundsnetzwerk). Ich würde vorschlagen, auch GovernmentalAuthority in eine Rolle umzuwandeln und die Verbindung "entityTypeComponent" durch "isResponsibleFor" zu ersetzen. Ich glaube, hier kommt man schnell in eine Grauzone, wo gewisse Objekte aus verschiedenen Sichtweisen sowohl Rollen als auch Entity Types sind...

- **http://www.snik.eu/ontology/bb/HealthCareInstitution** -> Das würde einen erneuten Rattenschwanz nach sich ziehen... Folgende Objekte wären dann auch Rollen: ,http://www.snik.eu/ontology/bb/Hospital
http://www.snik.eu/ontology/bb/Pharmacy, http://www.snik.eu/ontology/bb/GeneralPractice, http://www.snik.eu/ontology/bb/HealthInsuranceCompany, http://www.snik.eu/ontology/bb/HomeCareInstitution, http://www.snik.eu/ontology/bb/IndependentHealthRecordBank, http://www.snik.eu/ontology/bb/InpatientCareInstitution, http://www.snik.eu/ontology/bb/NursingCenter, http://www.snik.eu/ontology/bb/OutpatientCareInstitution, http://www.snik.eu/ontology/bb/RehabilitationCenter 
Ich finde, dass man das aber auch als Rolle interpretieren kann

- **http://www.snik.eu/ontology/bb/HealthcareServicesSpecificationProject** ist eine Arbeitsgruppe o.ä. keine Probleme bei Wechsel zu Rolle

- **http://www.snik.eu/ontology/bb/InternationalDICOMCommittee** - ein Kommittee;  Änderung zu Rolle würde falsche Relationen korrigieren (besitzt eine Relation, die von Rolle auf Function zeigt)

- http://www.snik.eu/ontology/bb/JointCommission eine non-Profit Organization;  Änderung zu Rolle würde falsche Relationen korrigieren (besitzt eine Relation, die von Rolle auf Function zeigt)

- http://www.snik.eu/ontology/bb/ResearchInstitution dieser Begriff wird nur auf  Seite 11 am Rande erwähnt, besitzt keine weiteren Beziehungen ist also isoliert. Ummodellierung als Rolle ist kein Problem, nur ohne weitere Relationen ist dieses Tripel nutzlos

**Comment by AlfredWinter** [comment]
Ja, diesen Rattenschwanz hatten wir ja befürchtet. Aber Ihre Analyse zeigt ja, dass damit wirklich viele Fehler beseitigt werden. Die potenzielle Qualitätsverbesserung ist also offensichtlich. Fazit: Ran an’s Werk! AW
 
 
a-------------´v-----------------------------p
Universität Leipzig KöR
Medizinische Fakultät
Institut für Medizinische Informatik, Statistik und Epidemiologie
Härtelstraße 16-18
D-04107 Leipzig

Prof. Dr. Alfred Winter
Tel.:      +49 341-97-16107, 
Mobil: +49 1515 5019248
E-Mail: alfred.winter@imise.uni-leipzig.de 
web: www.imise.uni-leipzig.de, www.3lgm2.de
facebook: www.facebook.com/medinfo.unileipzig 
twitter: @MedizinischeL
instagram: medinfo.unileipzig
 
 
Rektorin der Universität Prof. Dr. med. Beate A. Schücking, Ritterstraße 26, 04109 Leipzig 
Zuständige Aufsichtsbehörde: Sächsisches Staatsministerium für Wissenschaft und Kunst, Wigardstraße 17, 01097 Dresden, www.smwk.sachsen.de
 
Von: LudwigWermke [mailto:notifications@github.com] 
Gesendet: Freitag, 22. Februar 2019 15:29
An: IMISE/snik-ontology <snik-ontology@noreply.github.com>
Cc: AlfredWinter <alfred.winter@imise.uni-leipzig.de>; Author <author@noreply.github.com>
Betreff: Re: [IMISE/snik-ontology] http://www.snik.eu/ontology/bb/InternationalDICOMCommittee (#258)
 
Wechseln von Organization zu Rolle würde folgenden Rattenschwanz nach sich ziehen (noch nicht fertig):
A) Ummodellieren von sämtlichen Subklassen:
·         http://www.snik.eu/ontology/bb/EuroRec (eine Institution, also eher Rolle; Änderunge zu Rolle würde falsche Relationen korrigieren (besitzt eine Relation, die von Rolle auf Function zeigt)
·         http://www.snik.eu/ontology/bb/Cchit (eine non-profit-Organization; Änderung zu Rolle würde falsche Relationen korrigieren (besitzt eine Relation, die von Rolle auf Function zeigt)
·         http://www.snik.eu/ontology/bb/Ccow: eine Arbeitsgruppe vmtl an einm Unterpunkt zu HL7; Die Beziehung "isAssociatedWith" (-> HL7-Spaß (Entity-Type)) kann evtl. Probleme verursachen, da sich mir aus dem Meta-model nicht erschließt, ob eine Beziehung isAssociatedWith zwischen "Role" und "Entity Type" erlaubt is
·         http://www.snik.eu/ontology/bb/Cen - irgendein Kommittee; Änderung zu Rolle würde falsche Relationen korrigieren (besitzt eine Relation, die von Rolle auf Function zeigt)
·         http://www.snik.eu/ontology/bb/Ihe - eine Organisation, definitiv falsch modelliert. Muss eine Rolle sein. Änderung kann Probleme verursachen: es existieren zwei Beziehungen "isAssociatedWith" zu einem "Entity Type" sowie eine Inverse Beziehung "isAssociatedWith" mit IHE Connect-a-thon (Entity Type)
·         http://www.snik.eu/ontology/bb/FundingInstitution (laut BB (Strg+F) nur zweimal erwähnt und definitiv nur eine Aufgabe und daher falsch modelliert. Definitv keine Subklasse von Organization vmtl auch nicht von HIS Interessenvertreter; weitere Modellierungsprobleme bei den relationen zu anderen Klassen, die aber vertretba sind) Man müsse hier recherchieren, wo das alles neu eingehängt werden soll
·         http://www.snik.eu/ontology/bb/GovernmentalAuthority: wird im bb nur in Nebensätzen erwähnt, Genaugenommen handelt es sich hier um die Regierung/den Teil der Exekutiven, der u.A. für Health-Care-Networks verantwortlich ist (dahe auch die Verbidnung zu Gesundheitsversorgundsnetzwerk). Ich würde vorschlagen, auch GovernmentalAuthority in eine Rolle umzuwandeln und die Verbindung "entityTypeComponent" durch "isResponsibleFor" zu ersetzen. Ich glaube, hier kommt man schnell in eine Grauzone, wo gewisse Objekte aus verschiedenen Sichtweisen sowohl Rollen als auch Entity Types sind...
·         http://www.snik.eu/ontology/bb/HealthCareInstitution -> Das würde einen erneuten Rattenschwanz nach sich ziehen... Folgende Objekte wären dann auch Rollen: ,http://www.snik.eu/ontology/bb/Hospital
http://www.snik.eu/ontology/bb/Pharmacy, http://www.snik.eu/ontology/bb/GeneralPractice, http://www.snik.eu/ontology/bb/HealthInsuranceCompany, http://www.snik.eu/ontology/bb/HomeCareInstitution, http://www.snik.eu/ontology/bb/IndependentHealthRecordBank, http://www.snik.eu/ontology/bb/InpatientCareInstitution, http://www.snik.eu/ontology/bb/NursingCenter, http://www.snik.eu/ontology/bb/OutpatientCareInstitution, http://www.snik.eu/ontology/bb/RehabilitationCenter
Ich finde, dass man das aber auch als Rolle interpretieren kann
·         http://www.snik.eu/ontology/bb/HealthcareServicesSpecificationProject ist eine Arbeitsgruppe o.ä. keine Probleme bei Wechsel zu Rolle
·         http://www.snik.eu/ontology/bb/InternationalDICOMCommittee - ein Kommittee; Änderung zu Rolle würde falsche Relationen korrigieren (besitzt eine Relation, die von Rolle auf Function zeigt)
·         http://www.snik.eu/ontology/bb/JointCommission eine non-Profit Organization; Änderung zu Rolle würde falsche Relationen korrigieren (besitzt eine Relation, die von Rolle auf Function zeigt)
·         http://www.snik.eu/ontology/bb/ResearchInstitution dieser Begriff wird nur auf Seite 11 am Rande erwähnt, besitzt keine weiteren Beziehungen ist also isoliert. Ummodellierung als Rolle ist kein Problem, nur ohne weitere Relationen ist dieses Tripel nutzlos

**Comment by KonradHoeffner** [comment]
Anna und Ludwig sind nicht mehr da, daher spiele ich den Ball mal @FranziskaJahn und @BirgitSNIK zu.

**Comment by KonradHoeffner** [comment]
Mittlerweile als Teil von #495 erledigt.
