### ISSUE TITLE
http://www.snik.eu/ontology/ob/DefiningProjectOrganization

### ISSUE THREAD

**Issue by AnnaLoerke** [snikproject/ontology#267]
The class http://www.snik.eu/ontology/ob/DefiningProjectOrganization has [incorrect/missing attribute values | incorrect/missing relations to other classes, other (please specify and remove not applicable ones).]

DefiningProjectOrganization ist als SupTop von Rolle modelliert, ist aber eigentlich eine Funktion und auch als solche modelliert.
Die Relation updates zu Projektmanager ist aber trotzdem nicht möglich und muss entweder ummodelliert oder in eine textuelle Beschreibung in der Description überführt werden.

**Comment by KonradHoeffner** [comment]
Ich nehme mich mal raus, da man dafür Fachkenntnis von ob braucht.

**Comment by KonradHoeffner** [comment]
@BirgitSNIK, @FranziskaJahn: Möchte das eine von euch machen? Oder wer könnte das sonst übernehmen?

**Comment by KonradHoeffner** [comment]
Ist mittlerweile eine Aufgabe und wird in #496 behandelt.
