### ISSUE TITLE
http://www.snik.eu/ontology/bb/StrategicHospitalGoal

### ISSUE THREAD

**Issue by AlfredWinter** [snikproject/ontology#279]
The class http://www.snik.eu/ontology/bb/StrategicHospitalGoal has [incorrect/missing attribute values | incorrect/missing relations to other classes, other (please specify and remove not applicable ones).]

**Details**
Das ist ein Unterbegriff von http://www.snik.eu/ontology/he/StrategischesUnternehmensziel . Da http://www.snik.eu/ontology/he/StrategischesUnternehmensziel aber in anderer Ontologie geht einfaches subClassOff nicht. Also andere Lösung suchen.

**Comment by FranziskaJahn** [comment]
Für solche Fälle könnten wir doch die die skos:broader bzw. skos:narrower-Relationen verwenden.

**Comment by AlfredWinter** [comment]
GenauNachricht wurde von einem schlauen Telefon gesendet.Message sent by a smart phone.a-------------´v-----------------------------pUniversität Leipzig KöRMedizinische FakultätInstitut für Medizinische Informatik, Statistik und EpidemiologieHärtelstraße 16-18D-04107 LeipzigProf. Dr. Alfred WinterTel.:      +49 341-97-16107, Mobil: +49 1515 5019248E-Mail: alfred.winter@imise.uni-leipzig.de web: www.imise.uni-leipzig.de, www.3lgm2.defacebook: www.facebook.com/medinfo.unileipzig twitter: @MedInfoLinstagram: medinfo.unileipzig  Rektorin der Universität Prof. Dr. med. Beate A. Schücking, Ritterstraße 26, 04109 Leipzig Zuständige Aufsichtsbehörde: Sächsisches Staatsministerium für Wissenschaft und Kunst, Wigardstraße 17, 01097 Dresden, www.smwk.sachsen.d<div>
</div><div>
</div><div>-------- Ursprüngliche Nachricht --------</div><div>Von: FranziskaJahn <notifications@github.com> </div><div>Datum: 11.10.19  13:26  (GMT+01:00) </div><div>An: IMISE/snik-ontology <snik-ontology@noreply.github.com> </div><div>Cc: AlfredWinter <alfred.winter@imise.uni-leipzig.de>, Author <author@noreply.github.com> </div><div>Betreff: Re: [IMISE/snik-ontology] http://www.snik.eu/ontology/bb/StrategicHospitalGoal (#279) </div><div>
</div>Für solche Fälle könnten wir doch die die skos:broader bzw. skos:narrower-Relationen verwenden.

**Comment by KonradHoeffner** [comment]
Nach den [Modellierungsregeln](https://wiki.imise.uni-leipzig.de/Projekte/SNIK/ontologie/modellierungsregeln) passt hier bb:StrategicHospitalGoal skos:broadMatch. Wurde in den match graph über match.nt hinzugefügt.

**Comment by AlfredWinter** [comment]
An der Verbindung steht jetzt CloseMatch. Aber es müsste doch skos:broadMatch sein. Ist das o.k.?

**Comment by AlfredWinter** [comment]
Sorry, habs (glaube ich) verstanden. o.k.

**Comment by KonradHoeffner** [comment]
Hm Sie haben Recht, vielleicht hatte ich das noch nicht in den Endpunkt gestellt. Ich lade das mal neu hoch.

**Comment by KonradHoeffner** [comment]
So, jetzt ist es im SPARQL Endpunkt aktualisiert und auf https://www.snik.eu/ontology/bb/StrategicHospitalGoal sichtbar.
