### ISSUE TITLE
http://www.snik.eu/ontology/bb/HospitalManagement

### ISSUE THREAD

**Issue by AlfredWinter** [snikproject/ontology#281]
The class http://www.snik.eu/ontology/bb/HospitalManagement has [incorrect/missing attribute values | incorrect/missing relations to other classes, other (please specify and remove not applicable ones).]

**Details**
1. Bitte eine Rolle suchen, die dafür verantwortlich ist.
2. der Closematch zu http://www.snik.eu/ontology/ciox/Vorstand ist falsch; denn das ist eine Rolle und hier haben wir eine Funcition. Aber der Vorstand ist die Rolle, die ich unter 1. erbeten habe.

**Comment by AnnaLoerke** [comment]
Wäre aus Ihrer Sicht http://www.snik.eu/ontology/bb/HospitalManagementStaff eine passende Rolle?

**Comment by AlfredWinter** [comment]
Nein, nicht wirklich, bitte kurz in der Besprechung ansprechen. 
AW

**Comment by AlfredWinter** [comment]
Hospital Management Staff verwenden. "Wir verwenden das als Top Management" in Beschreibung einfügen. CEO und CFO als roleComponent.

**Comment by AlfredWinter** [comment]
Hospital Management Staff  in Top management umbenennen.

**Comment by AnnaLoerke** [comment]
Der http://www.snik.eu/ontology/ciox/Vorstand scheint gar nicht mehr angezeigt zu werden und es existieren auch nur zwei closeMatch ohne jegliche andere Information. Wurde der ersetzt und nicht korrekt gelöscht? Was soll mit ihm passieren?

Umbenennung sowie Einfügen der ResposibleFor-Beziehung und der beiden roleComponent ist erfolgt.

**Comment by KonradHoeffner** [comment]
Zuerst sah es für mich so aus als hätte es jemand entweder gelöscht oder umbenannt aber dabei nur den CIOX-Graphen genommen, allerdings sind diese zwei Closematch-Tripel auch im CIOX-Graph. Hat denn irgendwer von uns etwas mit dem Vorstand zu tun gehabt? Kannst du mal gucken, ob es den CIOX-Vorstand jetzt unter anderem Namen gibt?

**Comment by AlfredWinter** [comment]
@BirgitSNIK , @FranziskaJahn : Please investigate.

**Comment by KonradHoeffner** [comment]
- [ ] HospitalManagementStaff in TopManagement umbenennen
- [ ] hinzufügen: bb:TopManagement meta:isResponsibleFor http://www.snik.eu/ontology/bb/HospitalManagement

**Comment by KonradHoeffner** [comment]
Dann ist das ja schon erledigt.
