### ISSUE TITLE
http://www.snik.eu/ontology/ob/Vendor

### ISSUE THREAD

**Issue by AnnaLoerke** [snikproject/ontology#288]
Hat als SubTop-Class Function, ist aber sonst als Rolle modelliert. Dauerhaft als Rolle scheint auch fachlich angebracht.

SubTop-Class Vererbung kontrollieren.

**Comment by FranziskaJahn** [comment]
subClassOf-Beziehung zu Information Management entfernen, diese ist falsch. Zusätzlich: Vendor uses TenderVetting ersetzen durch Vendor isInvolvedIn TenderVetting.

**Comment by KonradHoeffner** [comment]
Ist mittlerweile auch eine Rolle und Teil von #496.
