### ISSUE TITLE
Functions in bb ohne uses oder updates Beziehungen diese hinzufügen

### ISSUE THREAD

**Issue by KonradHoeffner** [snikproject/ontology#290]
Alle Functions die weder uses noch updates-Beziehungen haben abarbeiten. Dabei wird man wohl auch in die Bücher schauen müssen.

Verallgemeinerung der Issue #273 auf das ganze bb, dort wird alles erklärt.

**Comment by KonradHoeffner** [comment]
@ThomasPause: Kannst du das investigaten?

**Comment by ThomasPause** [comment]
erstmal Tabelle angelegt, benötigt Rücksprache mit FJ

https://docs.google.com/spreadsheets/d/1S6z3eWL_tLFnH7u7SFnqh0mt1A88tzNiKWvkSKamfHA/edit#gid=0

**Comment by KonradHoeffner** [comment]
Auch möglich als Bachelorarbeit.
