### ISSUE TITLE
ob:Bid meta:functionComponent ob:Vendor

### ISSUE THREAD

**Issue by AlfredWinter** [snikproject/ontology#303]
The edge "ob:Bid meta:functionComponent ob:Vendor" is incorrect.

**Details**
prüfen

**Comment by AnnaLoerke** [comment]
ob:Vendor müsste Rolle sein und nicht Funktion. Es erbt aber von einer Funktion und nähere Untersuchungen sind nötig.
Passend wäre danach ob:Vendor meta:isResponsibleForEntityType ob:Bid

**Comment by KonradHoeffner** [comment]
ob:Vendor meta:isResponsibleForEntityType ob:Bid ist inzwischen auch da.
