### ISSUE TITLE
bb:Consultant meta:farNeighbour bb:Patient

### ISSUE THREAD

**Issue by AlfredWinter** [snikproject/ontology#304]
The edge "bb:Consultant meta:farNeighbour bb:Patient" is incorrect.

**Details**
"farNeighbour" muss ersetzt werden

**Comment by KonradHoeffner** [comment]
Das ist ein Anzeigefehler im LodView, ich kümmere mich darum.

**Comment by KonradHoeffner** [comment]
Fixed in https://github.com/IMISE/snik-lodview/commit/3c35b6f0bdcd5e265f0145b0dd4b7d1c0dd15237.

**Comment by KonradHoeffner** [comment]
The problem of farNeighbour relations being shown occurs again.

**Comment by KonradHoeffner** [comment]
SELECT DISTINCT ?g {GRAPH ?g {?x meta:farNeighbour ?y.}}

The derived graph needs to be excluded from the graph group.

**Comment by KonradHoeffner** [comment]
DB.DBA.RDF_GRAPH_GROUP_DEL ('http://www.snik.eu/ontology', 'http://www.snik.eu/ontology/derived');

Also deleted the graph, as it is not used right now and is outdated anyways.
