### ISSUE TITLE
Unterklassen von bb:InformationManagement tiefer hängen

### ISSUE THREAD

**Issue by KonradHoeffner** [snikproject/ontology#366]
Momentan gibt es 96 direkte Unterklassen von bb:InformationManagement:

```
SELECT COUNT(DISTINCT(?u))
{
 ?u rdfs:subClassOf bb:InformationManagement.
}
```

Unterklassen
--
http://www.snik.eu/ontology/bb/Customizing
http://www.snik.eu/ontology/bb/CobitDomain
http://www.snik.eu/ontology/bb/HisBudgetPlanning
http://www.snik.eu/ontology/bb/HisCertification
http://www.snik.eu/ontology/bb/HisOperation
http://www.snik.eu/ontology/bb/ItInvestmentJustification
http://www.snik.eu/ontology/bb/ItInvestmentPlanning
http://www.snik.eu/ontology/bb/ItServiceManagement
http://www.snik.eu/ontology/bb/ItSupport
http://www.snik.eu/ontology/bb/ItilServiceLifecycle
http://www.snik.eu/ontology/bb/ReportingToTheCEO
http://www.snik.eu/ontology/bb/AccessControl
http://www.snik.eu/ontology/bb/AdHocMonitoring
http://www.snik.eu/ontology/bb/AdoptionOfProjectResult
http://www.snik.eu/ontology/bb/AnalysisAndAssessmentOfTheCurrentHISState
http://www.snik.eu/ontology/bb/ApprovalToStrategicInformationManagementPlan
http://www.snik.eu/ontology/bb/ChangeManagement
http://www.snik.eu/ontology/bb/ConfigurationManagement
http://www.snik.eu/ontology/bb/ContinualServiceImprovement
http://www.snik.eu/ontology/bb/ContinuousHISAuditing
http://www.snik.eu/ontology/bb/ContinuousQualityImprovementProcess
http://www.snik.eu/ontology/bb/CreationOfStrategicInformationManagementPlan
http://www.snik.eu/ontology/bb/DataProtection
http://www.snik.eu/ontology/bb/DeliveringOfCustomerCenteredServices
http://www.snik.eu/ontology/bb/DeploymentOfStrategicInformationManagementPlan
http://www.snik.eu/ontology/bb/DesigningCustomerCenteredServices
http://www.snik.eu/ontology/bb/EstablishAndPromoteTheStrategicInformationManagementPlan
http://www.snik.eu/ontology/bb/EstablishingReferentialIntegrity
http://www.snik.eu/ontology/bb/ExecutionOfAnITEvaluationStudy
http://www.snik.eu/ontology/bb/FailureManagement
http://www.snik.eu/ontology/bb/FulfillmentOfLawsRelevantToInformationManagement
http://www.snik.eu/ontology/bb/FulfillmentOfTheExpectationsOfDifferentStakeholders
http://www.snik.eu/ontology/bb/ImprovingCustomerCenteredServices
http://www.snik.eu/ontology/bb/IncidentAnalysis
http://www.snik.eu/ontology/bb/IncidentManagement
http://www.snik.eu/ontology/bb/IncidentTaking
http://www.snik.eu/ontology/bb/InformationAndKnowledgeLogistics
http://www.snik.eu/ontology/bb/InformationManagementInHealthCareNetworks
http://www.snik.eu/ontology/bb/InformationManagementInHospitals
http://www.snik.eu/ontology/bb/InformationProcessing
http://www.snik.eu/ontology/bb/InformationStorage
http://www.snik.eu/ontology/bb/LifeCycleManagementOfStrategicInformationManagementPlan
http://www.snik.eu/ontology/bb/LongTermHISPlanning
http://www.snik.eu/ontology/bb/MakingABackup
http://www.snik.eu/ontology/bb/ManagementOfUserAccounts
http://www.snik.eu/ontology/bb/MessageEncryption
http://www.snik.eu/ontology/bb/ModelingInformationSystems
http://www.snik.eu/ontology/bb/MonitoringTheProjectProgress
http://www.snik.eu/ontology/bb/NetworkManagement
http://www.snik.eu/ontology/bb/NetworkMonitoring
http://www.snik.eu/ontology/bb/OperationalHISDirecting
http://www.snik.eu/ontology/bb/OperationalHISMonitoring
http://www.snik.eu/ontology/bb/OperationalHISPlanning
http://www.snik.eu/ontology/bb/PermanentMonitoring
http://www.snik.eu/ontology/bb/PlanningOfBuildings
http://www.snik.eu/ontology/bb/PlanningOfFinances
http://www.snik.eu/ontology/bb/PlanningOfOrganizationalProcedures
http://www.snik.eu/ontology/bb/PlanningOfOrganizationalStructures
http://www.snik.eu/ontology/bb/PlanningOfRooms
http://www.snik.eu/ontology/bb/PlanningOfStaff
http://www.snik.eu/ontology/bb/PortfolioManagement
http://www.snik.eu/ontology/bb/ProblemManagement
http://www.snik.eu/ontology/bb/ProblemSolving
http://www.snik.eu/ontology/bb/ProjectCompletion
http://www.snik.eu/ontology/bb/ProjectConflictManagement
http://www.snik.eu/ontology/bb/ProjectExecution
http://www.snik.eu/ontology/bb/ProjectInitiation
http://www.snik.eu/ontology/bb/ProjectPlanning
http://www.snik.eu/ontology/bb/ProjectResourceAllocation
http://www.snik.eu/ontology/bb/ProjectTimeAllocation
http://www.snik.eu/ontology/bb/ProvidingCustomerCenteredServices
http://www.snik.eu/ontology/bb/ReportToTheHospitalsBoardOfDirectors
http://www.snik.eu/ontology/bb/RiskManagement
http://www.snik.eu/ontology/bb/ServiceAssetManagement
http://www.snik.eu/ontology/bb/ServiceDesign
http://www.snik.eu/ontology/bb/ServiceDeskManagement
http://www.snik.eu/ontology/bb/ServiceOperation
http://www.snik.eu/ontology/bb/ServiceStrategy
http://www.snik.eu/ontology/bb/ServiceTransition
http://www.snik.eu/ontology/bb/ShortTermHISPlanning
http://www.snik.eu/ontology/bb/SoftwareDevelopment
http://www.snik.eu/ontology/bb/StorageService
http://www.snik.eu/ontology/bb/StrategicAlignment
http://www.snik.eu/ontology/bb/StrategicHISDirecting
http://www.snik.eu/ontology/bb/StrategicHISMonitoring
http://www.snik.eu/ontology/bb/StrategicHISPlanning
http://www.snik.eu/ontology/bb/SystematicInformationProcessing
http://www.snik.eu/ontology/bb/TacticalHISDirecting
http://www.snik.eu/ontology/bb/TacticalHISMonitoring
http://www.snik.eu/ontology/bb/TacticalHISPlanning
http://www.snik.eu/ontology/bb/TransactionManagement
http://www.snik.eu/ontology/bb/TroubleShooting
http://www.snik.eu/ontology/bb/UpdatingTheStrategicInformationManagementPlan
http://www.snik.eu/ontology/bb/UseOfStrategicInformationManagementPlan
http://www.snik.eu/ontology/bb/UserRequirementsAnalysis
http://www.snik.eu/ontology/bb/UserTraining

**Comment by ThomasPause** [comment]
Tabelle zur Überarbeitung der Relationen:
https://docs.google.com/spreadsheets/d/1A7THvy5Le23aQF_6pE0AbS6ov3WrlCvMBb2ANz2hewc/edit?usp=sharing

**Comment by FranziskaJahn** [comment]
Bisher waren folgende Beziehungen modelliert:
![grafik](https://user-images.githubusercontent.com/23310406/83021199-f273cc80-a029-11ea-8be8-be218d695bf0.png)
![grafik](https://user-images.githubusercontent.com/23310406/83021226-f99ada80-a029-11ea-817f-7ef504b81d55.png)
![grafik](https://user-images.githubusercontent.com/23310406/83021236-fef82500-a029-11ea-9f5b-f2de07b8f48e.png)
![grafik](https://user-images.githubusercontent.com/23310406/83021248-03bcd900-a02a-11ea-8b57-1ba5e145103c.png)
![grafik](https://user-images.githubusercontent.com/23310406/83021258-091a2380-a02a-11ea-9b32-e48c621e4cb7.png)

**Comment by KonradHoeffner** [comment]
Von den 96 Einträgen wurden 57 ausgefüllt. Diese wurden gemäß der Tabelle umgehängt.

1. Backup (20200825)
2. Insert new triples
3. Delete old triples
[delete.txt](https://github.com/IMISE/snik-ontology/files/5123267/delete.txt)
[insert.txt](https://github.com/IMISE/snik-ontology/files/5123271/insert.txt)

**Comment by KonradHoeffner** [comment]
Was soll mit den restlichen Einträgen passieren?

**Comment by KonradHoeffner** [comment]
http://www.snik.eu/ontology/bb/ItServiceManagement soll gelöscht werden.

**Comment by KonradHoeffner** [comment]
Analog auch im orangenen Buch: #395.

**Comment by KonradHoeffner** [comment]
In einer späteren jour fixe gemeinsam durchgehen.

**Comment by KonradHoeffner** [comment]
SNIK Jour Fixe 2021-05-19: 16 erledigt in Tabelle.
@KonradHoeffner : Umsetzen.

**Comment by KonradHoeffner** [comment]
Es sind jetzt alle Änderungen entschieden und müssen nur noch von mir umgesetzt werden.

**Comment by KonradHoeffner** [comment]
Es sind wieder drei aufgetaucht:

* http://www.snik.eu/ontology/bb/CobitProcess
* http://www.snik.eu/ontology/bb/InformationManagementInHealthCareNetworks
* http://www.snik.eu/ontology/bb/InformationManagementInHospitals
