### ISSUE TITLE
bb:StrategicInformationManagement meta:functionComponent bb:StrategicHISPlanning

### ISSUE THREAD

**Issue by AlfredWinter** [snikproject/ontology#400]
Problem with the edge [bb:StrategicInformationManagement meta:functionComponent bb:StrategicHISPlanning](http://www.snik.eu/ontology/bb/StrategicInformationManagement) ([OntoWiki URL](https://www.snik.eu/ontowiki/view/?r=http://www.snik.eu/ontology/bb/StrategicInformationManagement&m=http://www.snik.eu/ontology/bb)):

Diskutieren: hier gibt es auch eine subclassof beziehung. Wir müssen uns für eine entscheiden.

**Comment by KonradHoeffner** [comment]
Das gleiche gilt für bb:StrategicHISMonitoring, beide sind Unterklassen von bb:StrategicInformationManagement.
bb:StrategicHISDirecting ist allerdings nicht über die Subklassenbeziehung mit bb:StrategicInformationManagement verbunden sondern mit meta:Function.

**Comment by KonradHoeffner** [comment]
Analog zu den Klassen aus dem BB (siehe https://docs.google.com/spreadsheets/d/1A7THvy5Le23aQF_6pE0AbS6ov3WrlCvMBb2ANz2hewc/edit#gid=0):
- component of strategic information management, subclassof Beziehung löschen, an function hängen
