### ISSUE TITLE
bb:Monitoring rdfs:subClassOf bb:Management

### ISSUE THREAD

**Issue by AlfredWinter** [snikproject/ontology#412]
Problem with the edge [bb:Monitoring rdfs:subClassOf bb:Management](http://www.snik.eu/ontology/bb/Monitoring) ([OntoWiki URL](https://www.snik.eu/ontowiki/view/?r=http://www.snik.eu/ontology/bb/Monitoring&m=http://www.snik.eu/ontology/bb)):

Löschen. Das iist keine SubclassOf sondern Komponente (diese Beziehung besteht schon).

**Comment by KonradHoeffner** [comment]
Dann hat bb:Monitoring allerdings keine Oberklasse mehr, was laut unseren Modellierungsregeln nicht erlaubt ist. Haben Sie eine alternative Oberklasse, die ich einsetzen kann?

**Comment by AlfredWinter** [comment]
sie #413
