### ISSUE TITLE
Independent Health Record Bank isResponsibleForEntityType Electronic Health Record

### ISSUE THREAD

**Issue by KonradHoeffner** [snikproject/ontology#446]
`bb:IndependentHealthRecordBank meta:isResponsibleForEntityType bb:ElectronicHealthRecord.`

This triple does not conform to the meta model because the subject is an entity type.

Between two entity types we can only use meta:entityTypeComponent, meta:isBasedOn and meta:isAssociatedWith.

Change the property to meta:isAssociatedWith?

**Comment by KonradHoeffner** [comment]
Discussed in jour fixe 2020-11-17.

**Comment by KonradHoeffner** [comment]
> Finally, the non-centric strategy of “independent health banks” can be identified,
> although this model has not been implemented yet. This strategy stands out, because it is
> not centered on the mentioned stakeholders in health care. Comparable to normal banks,
> there are lots of independent health banks being responsible for managing lifetime EHRs
> without having any control over other parties. Since these banks are not part of the health
> care system, they remain neutral. In health care institutions, there would be no need to
> maintain archives of medical records. This is similar to taking money to the most trusted
> bank instead of keeping it in one‟s own safe. This bank will also take care, that only
> authorized parties will get (part of) the money.
Blue Book, Second Edition, Section 7.3.2.4 "The Strategy of Independent Health Banks", Page 192.

> The strategy of independent health banks is characterized by neutral actors that are responsible for managing the EHR, while 
> not being part of the actual health care system.
Blue Book, Second Edition, Section 7.7 "Summary", Page 199.

fr
Franziska Jahn
10:03 AM

Neutral IHRB actor isResponsible for Management of EHR
al
Alfred Winter (Leipzig)
10:05 AM

und: Neutral IHRB actor isResponsible for IndependentHealthRecordBank
fr
Franziska Jahn
10:05 AM

EHR component IHRB
fr
Franziska Jahn
10:06 AM

neutral IHRB provider

**Comment by KonradHoeffner** [comment]
```
bb:NeutralIhrbActor meta:isResponsibleFor bb:ManagementofEhr.
bb:NeutralIhrbActor meta:isResponsibleFor bb:IndependentHealthRecordBank.
```

**Comment by KonradHoeffner** [comment]
Added two new classes and connected them. @AlfredWinter , @FranziskaJahn : Please verify if that is correct, then this issue can be closed.

![snik-graph-issue-446](https://user-images.githubusercontent.com/839577/99407853-d9b8e500-28ef-11eb-83a6-ac630071f9dc.png)

**Comment by AlfredWinter** [comment]
es fehlt noch die component beziehung: EHR component of IHRB

**Comment by KonradHoeffner** [comment]
bb:ManagementOfEhr ist eine Aufgabe und bb:NeutralIhrbActor ist eine Rolle. Daher ist die Komponentenbeziehung nicht möglich. Gibt es eine Alternative?

**Comment by AlfredWinter** [comment]
Das ist ein guter Weg, das Problem zu lösen. Aber jetzt dämmert mir, dass wir hier ein grundlegenderes Thema haben. 

Eine IHRB ist -zumindest im weiteren Sinne -  zu Recht per subclassof als HealthCareInstitution modelliert (siehe beigelegte SNIK-Session). Bei den Institutionen interessiert uns doch im Zusammenhang mit dem Informationsmanagement, dass sie eine gewisse Aufgabe haben. Uns interessiert weniger, dass es Daten über sie gibt, die durch unsere Informationssysteme verarbeitet werden müssen. Wir haben diese Dinger aber als entity type modelliert. Das bedeutet aber, dass wir uns für "Informationen über" diese Dinger interessieren. Ich fürchte, das ist falsch und es wäre besser, alle diese Institutionen als Rolle zu modellieren. 

Wenn wir das täten, dann wäre die IHRB schlicht eine subClassOf von Health Care Institution als Rolle und wir bräuchten auch den NeutralIhrbActor nicht, könnten ihn aber auch als roleComponent von IHRB behalten.  

Wenn wir das tun wollen, dann müssen wir uns aber die Ränder der Wolke anschauen, die an der Health Care Institution hängt.
In der beigelegten Session sieht man zunächst mal den Patient, der als entityTypeComponent am Hospital hängt. Es ist nach der Anfangsüberlegung nach wie vor richtig, dass der Patient entity Type ist; denn wir interessieren uns bei den Informationssystemen für "Informationen über" ihn. Die Beziehugn von Health Care Institution zu Patient könnte dann durchaus "uses" und "updates" aber auch "associated with" oder auch leer sein. Dann müsste man sich noch die anderen Rollen anschauen, die am Patient hängen, z.B. Physician. Ein Physician wäre doch dann eigentlich eine roleComponent von hospital. Wenn man das hat, braucht man eigentlich keine unmittelbare Beziehung zwischen hosptial und Patitent mehr ...
Jetzt muss man sich auch bei den anderen an HealthCareInstitution hängenden Einrichtungen anschauen, was passiert, wenn das alles zur Rolle wird. z.B. "GeneralPractice". Jedesmal ist dann zu entscheiden, ob es problemlos rolle werden kann oder unbedingt entity type bleiben muss. 

Das würde ich gerne noch mal diskutieren.



[snik-session (13).zip](https://github.com/IMISE/snik-ontology/files/6037209/snik-session.13.zip)

**Comment by KonradHoeffner** [comment]
Das sieht nach einer aufwändigen Änderung aus, da die Unterklassen von Health Care Institution auch wieder Unterklassen haben, z.B. 
Health Care Institution -> Rehabilitation Center -> Nursing Center. Und die sind dann ja auch wieder mit anderen Konzepten verbunden mit Relationen, die dann auch wieder ungültig sind.
Aber ja, für mich klingt es auch besser, wenn ein Krankenhaus und eine Health Care Institution eine Rolle ist und Aufgaben hat.
Ich nehme mal @FranziskaJahn mit dazu und würde das dann gerne in der nächsten SNIK Jour Fixe besprechen.

**Comment by KonradHoeffner** [comment]
- löschen: IHRB subClassOf bb:HealthCareInstitution
- hinzufügen IHRB subClassOf meta:ApplicationComponent
- löschen: Neutral Independant Health Bank Actor und Verbindungen
- hinzufügen IHRB supports management of electronic health records
