### ISSUE TITLE
http://www.snik.eu/ontology/ob/InformationManagement

### ISSUE THREAD

**Issue by AlfredWinter** [snikproject/ontology#447]
Problem with the class [ob:InformationManagement](http://www.snik.eu/ontology/ob/InformationManagement) ([OntoWiki URL](https://www.snik.eu/ontowiki/view/?r=http://www.snik.eu/ontology/ob/InformationManagement&m=http://www.snik.eu/ontology/ob)):

Jetzt ist aber eine Situation erreicht, die ich eigentlich immer verhindern wollte. Wenn ich wissen will, was "InformationManagement" denn eigentlich ist, dann ist es doch ein guter Weg, sich zu InformationManagement den Star anzuschauen. Aber der liefert jetzt (wieder?) nahezu alles. Probieren Sie es mal aus. Das hilft einem ja nicht weiter.
 Habe ich das mit meinen Änderungswünschen jetzt verursacht?

**Comment by KonradHoeffner** [comment]
Das Problem bestand auch schon vorher, deswegen haben wir die Issue https://github.com/IMISE/snik-ontology/issues/395 eingeführt, um dieses Problem zu lösen. Die Domänenexperten müssen das nur mal nach und nach abarbeiten.
