### ISSUE TITLE
ob:InformationSystem meta:functionComponent ob:EnterpriseFunction

### ISSUE THREAD

**Issue by BirgitSNIK** [snikproject/ontology#454]
Problem with the edge [ob:InformationSystem meta:functionComponent ob:EnterpriseFunction](http://www.snik.eu/ontology/ob/InformationSystem) ([OntoWiki URL](https://www.snik.eu/ontowiki/view/?r=http://www.snik.eu/ontology/ob/InformationSystem&m=http://www.snik.eu/ontology/ob)):als Beziehung uses verwenden

**Comment by KonradHoeffner** [comment]
Erledigt.
