### ISSUE TITLE
ob:StrategicManagementOfInformationSystems meta:uses ob:InformationSystem

### ISSUE THREAD

**Issue by BirgitSNIK** [snikproject/ontology#455]
Problem with the edge [ob:StrategicManagementOfInformationSystems meta:uses ob:InformationSystem](http://www.snik.eu/ontology/ob/StrategicManagementOfInformationSystems) ([OntoWiki URL](https://www.snik.eu/ontowiki/view/?r=http://www.snik.eu/ontology/ob/StrategicManagementOfInformationSystems&m=http://www.snik.eu/ontology/ob)):das könnte zusätzlich noch updates sein

**Comment by KonradHoeffner** [comment]
Erledigt.
