### ISSUE TITLE
ob:StrategicInformationManagementPlanning meta:uses ob:InformationSystem

### ISSUE THREAD

**Issue by BirgitSNIK** [snikproject/ontology#456]
Problem with the edge [ob:StrategicInformationManagementPlanning meta:uses ob:InformationSystem](http://www.snik.eu/ontology/ob/StrategicInformationManagementPlanning) ([OntoWiki URL](https://www.snik.eu/ontowiki/view/?r=http://www.snik.eu/ontology/ob/StrategicInformationManagementPlanning&m=http://www.snik.eu/ontology/ob)):
das kann zusätzlich noch update sein

**Comment by KonradHoeffner** [comment]
Erledigt.
