### ISSUE TITLE
bb:InformationSystem meta:functionComponent bb:EnterpriseFunction

### ISSUE THREAD

**Issue by BirgitSNIK** [snikproject/ontology#457]
Problem with the edge [bb:InformationSystem meta:functionComponent bb:EnterpriseFunction](http://www.snik.eu/ontology/bb/InformationSystem) ([OntoWiki URL](https://www.snik.eu/ontowiki/view/?r=http://www.snik.eu/ontology/bb/InformationSystem&m=http://www.snik.eu/ontology/bb)):

Ich bin für enterpriseFuncion interprete & updates informationSystem. Die jetzige Beziehung ist gar nicht erlaubt.

**Comment by KonradHoeffner** [comment]
Das functionComponent-Tripel entfernt und dafür meta:EnterpriseFunction uses und updates bb:InformationSystem hinzugefügt.
