### ISSUE TITLE
bb:ClinicalDocumentation rdfs:subClassOf bb:Documentation

### ISSUE THREAD

**Issue by BirgitSNIK** [snikproject/ontology#458]
Problem with the edge [bb:ClinicalDocumentation rdfs:subClassOf bb:Documentation](http://www.snik.eu/ontology/bb/ClinicalDocumentation) ([OntoWiki URL](https://www.snik.eu/ontowiki/view/?r=http://www.snik.eu/ontology/bb/ClinicalDocumentation&m=http://www.snik.eu/ontology/bb)):

Vielleicht brauchen wir die Klinische Dokumentation als Entität und als Aufgabe!?! So ist es m.E. falsch.

**Comment by AlfredWinter** [comment]
sowohl bb:Documentation als auch die genannte Kante löschen
