### ISSUE TITLE
http://www.snik.eu/ontology/bb/CommunicationStandard

### ISSUE THREAD

**Issue by BirgitSNIK** [snikproject/ontology#459]
Problem with the class [bb:CommunicationStandard](http://www.snik.eu/ontology/bb/CommunicationStandard) ([OntoWiki URL](https://www.snik.eu/ontowiki/view/?r=http://www.snik.eu/ontology/bb/CommunicationStandard&m=http://www.snik.eu/ontology/bb)):
es wäre schön, wenn HL7 und DICOM nicht nur in der Definition als Beispiele für einen Kommunikationsstandard genannt würden sondern dies auch als subclassOf Beziehung modelliert wäre.

**Comment by KonradHoeffner** [comment]
bb:HL7Standard
bb:DicomStandard

**Comment by KonradHoeffner** [comment]
Done
