### ISSUE TITLE
bb:StrategicHISDirecting rdfs:subClassOf bb:StrategicInformationManagement

### ISSUE THREAD

**Issue by BirgitSNIK** [snikproject/ontology#460]
Problem with the edge [bb:StrategicHISDirecting rdfs:subClassOf bb:StrategicInformationManagement](http://www.snik.eu/ontology/bb/StrategicHISDirecting) ([OntoWiki URL](https://www.snik.eu/ontowiki/view/?r=http://www.snik.eu/ontology/bb/StrategicHISDirecting&m=http://www.snik.eu/ontology/bb)):

aus subClass sollten wir functionComponent machen

**Comment by KonradHoeffner** [comment]
Fertig.
