### ISSUE TITLE
http://www.snik.eu/ontology/ob/ProjectManagement

### ISSUE THREAD

**Issue by AlfredWinter** [snikproject/ontology#463]
Problem with the class [ob:ProjectManagement](http://www.snik.eu/ontology/ob/ProjectManagement) ([OntoWiki URL](https://www.snik.eu/ontowiki/view/?r=http://www.snik.eu/ontology/ob/ProjectManagement&m=http://www.snik.eu/ontology/ob)):

Description enthält doppelten Satz. korrigieren.
AW

**Comment by KonradHoeffner** [comment]
Korrigiert.
