### ISSUE TITLE
he:Projektmanager meta:isResponsibleForFunction he:LeitungsaufgabeInformationsinfrastruktur

### ISSUE THREAD

**Issue by AlfredWinter** [snikproject/ontology#464]
Problem with the edge [he:Projektmanager meta:isResponsibleForFunction he:LeitungsaufgabeInformationsinfrastruktur](http://www.snik.eu/ontology/he/Projektmanager) ([OntoWiki URL](https://www.snik.eu/ontowiki/view/?r=http://www.snik.eu/ontology/he/Projektmanager&m=http://www.snik.eu/ontology/he)):

Das stimmt nicht ganz. Dass, was wir als project-Manager verstehen, ist nicht für die Leitung der Informationsinfrastruktur zuständig. Das wäre der CIO. Möglichweise versteht Heinrich unter Projekt-manager etwas anderes als wir. Dann wäre aber der close-Match falsch. Bitte im Lehrbuch von Heinrich nachprüfen, wie das dort geschrieben steht und dann im Jour Fixe besprechen.

**Comment by KonradHoeffner** [comment]
### Definition
> Projektmanager (Projektleiter bzw. Projektkoordinator) sind Aufgabenträger für die Aufgabe IT-Projekte den vorgegebenen Planungszielen entsprechend zu gestalten und abzuwickeln wobei Kompetenz und Verantwortung im Wesentlichen durch die Projektorganisation und das Projektcontrolling bestimmt werden.

**Comment by AlfredWinter** [comment]
Bitte die Definition einfügen. 
Dann entfernen: edge he:Projektmanager meta:isResponsibleForFunction he:LeitungsaufgabeInformationsinfrastruktur
