### ISSUE TITLE
bb:TacticalInformationManagement rdfs:subClassOf bb:InformationManagement

### ISSUE THREAD

**Issue by AlfredWinter** [snikproject/ontology#466]
Problem with the edge [bb:TacticalInformationManagement rdfs:subClassOf bb:InformationManagement](http://www.snik.eu/ontology/bb/TacticalInformationManagement) ([OntoWiki URL](https://www.snik.eu/ontowiki/view/?r=http://www.snik.eu/ontology/bb/TacticalInformationManagement&m=http://www.snik.eu/ontology/bb)):

Das muss component of sein. Aber das hatten wir ja schon besprochen.

**Comment by KonradHoeffner** [comment]
Geändert.
