### ISSUE TITLE
http://www.snik.eu/ontology/bb/TacticalInformationManagement

### ISSUE THREAD

**Issue by AlfredWinter** [snikproject/ontology#467]
Problem with the class [bb:TacticalInformationManagement](http://www.snik.eu/ontology/bb/TacticalInformationManagement) ([OntoWiki URL](https://www.snik.eu/ontowiki/view/?r=http://www.snik.eu/ontology/bb/TacticalInformationManagement&m=http://www.snik.eu/ontology/bb)):

Einfügen: Close match zu http://www.snik.eu/ontology/ob/TacticalManagementOfInformationSystems

Wenn man sich um beide einen Stern macht, dann sieht man weitere Begriffe im BB und im OB, zwischen denen ein Close match modelliert werden muss.

**Comment by KonradHoeffner** [comment]
Kante ist hinzugefügt. Die anderen gab es schon, die wurden nur von SNIK Graph nicht mit angezeigt beim Star, das ist jetzt auch behoben.
![Uploading star-closematch.png…]()
