### ISSUE TITLE
ob:TacticalManagementOfInformationSystems rdfs:subClassOf ob:InformationManagement

### ISSUE THREAD

**Issue by AlfredWinter** [snikproject/ontology#468]
Problem with the edge [ob:TacticalManagementOfInformationSystems rdfs:subClassOf ob:InformationManagement](http://www.snik.eu/ontology/ob/TacticalManagementOfInformationSystems) ([OntoWiki URL](https://www.snik.eu/ontowiki/view/?r=http://www.snik.eu/ontology/ob/TacticalManagementOfInformationSystems&m=http://www.snik.eu/ontology/ob)):

auch hier ein component statt subClass (gilt im OB auch für strategic und operational IM

**Comment by KonradHoeffner** [comment]
Geändert für taktisches, strategisches und operatives IM.
