### ISSUE TITLE
bb:DesigningCustomerCenteredServices rdfs:subClassOf bb:ItServiceManagement

### ISSUE THREAD

**Issue by AlfredWinter** [snikproject/ontology#469]
Problem with the edge [bb:DesigningCustomerCenteredServices rdfs:subClassOf bb:ItServiceManagement](http://www.snik.eu/ontology/bb/DesigningCustomerCenteredServices) ([OntoWiki URL](https://www.snik.eu/ontowiki/view/?r=http://www.snik.eu/ontology/bb/DesigningCustomerCenteredServices&m=http://www.snik.eu/ontology/bb)):

ändern zu roleComponent

**Comment by AlfredWinter** [comment]
sorry, muss functionComponent sein

**Comment by KonradHoeffner** [comment]
Erledigt.
