### ISSUE TITLE
bb:ItilServiceLifecycle rdfs:subClassOf bb:ItServiceManagement

### ISSUE THREAD

**Issue by AlfredWinter** [snikproject/ontology#470]
Problem with the edge [bb:ItilServiceLifecycle rdfs:subClassOf bb:ItServiceManagement](http://www.snik.eu/ontology/bb/ItilServiceLifecycle) ([OntoWiki URL](https://www.snik.eu/ontowiki/view/?r=http://www.snik.eu/ontology/bb/ItilServiceLifecycle&m=http://www.snik.eu/ontology/bb)):

ändern zu roleComponent

**Comment by AlfredWinter** [comment]
sorry, muss functionComponent sein

**Comment by KonradHoeffner** [comment]
Erledigt.
