### ISSUE TITLE
bb:DeliveringOfCustomerCenteredServices rdfs:subClassOf bb:ItServiceManagement

### ISSUE THREAD

**Issue by AlfredWinter** [snikproject/ontology#471]
Problem with the edge [bb:DeliveringOfCustomerCenteredServices rdfs:subClassOf bb:ItServiceManagement](http://www.snik.eu/ontology/bb/DeliveringOfCustomerCenteredServices) ([OntoWiki URL](https://www.snik.eu/ontowiki/view/?r=http://www.snik.eu/ontology/bb/DeliveringOfCustomerCenteredServices&m=http://www.snik.eu/ontology/bb)):

ändern zu roleComponent

**Comment by AlfredWinter** [comment]
sorry, muss functionComponent sein

**Comment by KonradHoeffner** [comment]
Erledigt.
