### ISSUE TITLE
IT-Service

### ISSUE THREAD

**Issue by AlfredWinter** [snikproject/ontology#474]
Ich hätte gerne (nach Diskussion im Jour Fixe):

den entity-Type "IT-Service" 
- Quelle: Neues Blaues Buch
- Beschreibung: "Built on top of strategic and tactical information management, operational information management thus offers users comprehensive services. These services go beyond simply delivering hardware and software. Rather, they are designed to help users use these components in a way that is helpful for their professional work. Such services are also known as IT services. Thus, the information management department of a health care facility is an IT service provider that delivers IT services to its customers, the users of the facility's information system. The management activities that serve to provide quality IT services are grouped under the term IT service management (ITSM). So, IT service management has the task to design, provide, deliver and improve such customer-centered services. The IT Infrastructure Library (ITIL) is the de-facto standard framework for IT service management. ITIL was developed for the British Government in order to define best practices for all governmental computing centers."
- Beziehungen: 
* bb/DesigningCustomerCenteredServices updates it-services
* bb/ItilServiceLifecycle updates/uses it-services
* bb/DeliveringOfCustomerCenteredServices uses it-services

Und einen entity Type "IT-Service-Art.
- Beziehung: IT-service subClassOf IT-Service-Art.
- Instanzen (jeweils mit Definition in Klammern) (Quelle ist der Servicekatalog des Bereich 1 des UKL): 
* Applikationsbetreuung (Applikationsbetreuung umfasst den Betrieb in den Rechenzentren des Bereiches 1 (bei Client-Server-Systemen) bzw. auf den Client-PCs, Sicherstellung der Aktualität der Software (update-Service etc.), die Bereitstellung eines Ansprechpartners aus dem Bereich 1 (Administrator), die Möglichkeit, Fehler (incidents) und Anfragen (service requests) am IT ServiceDesk zu platzieren, die Möglichkeit, neue Anforderungen zur Umsetzung im Bereich 1 zu beantragen (IT Change Management-Verfahren))
* Hardware-Hosting (Hardware-Hosting umfasst die Bereitstellung eines (virtuellen) Servers oder einer (virtuellen) Maschine in den Rechenzentren des Bereiches 1, Sicherstellung der Aktualität des Betriebssystems (abhängig vom vereinbarten ServiceLevel))
* Applikation-Hosting (Applikation-Hosting umfasst Bereitstellung der Applikation auf einem (virtuellen) Server oder einer (virtuellen) Maschine in den Rechenzentren des Bereiches 1, Bereitstellung einer lokalen Installation auf Client-PCs- Sicherungsmaßnahmen im Rahmen des vereinbarten ServiceLevels)
* administrativer Support (administrativer Support umfasst die Beschaffung von Lizenzen- ggf. Begleitung der Installation (Zurverfügungstellung von Administrationsrechten))
* interner IT-Service (ein interner IT-Service ist eine Aktivität des Bereiches 1, der notwendig ist, um andere IT-Services bereitszustellen (enabling services) und von Kunden nicht explizit gebucht werden kann)

**Comment by AlfredWinter** [comment]
Quelle der Instanzen: noch ergänzen: Version: 1.1, Stand: 13.06.2013

**Comment by KonradHoeffner** [comment]
Soll das beides in die bb-Ontologie?
Die erste Klasse hat nur eine englische Beschreibung, die zweite eine Deutsche, soll das so sein?

**Comment by AlfredWinter** [comment]
Gibt es eine Oberklasse für die IT-Service-Art oder soll das direkt unter meta:EntityType hängen?
>direkt unter meta:EntityType
IT-Service-Art, ist da mit "Art" Typ gemeint? Dann könnte man das doch als Unterklassen modellieren statt als zwei Klassen mit Instanzen, oder?
>darüber muss ich nachdenke. Aber nicht jetzt.

**Comment by KonradHoeffner** [comment]
Ist jetzt mit Unterklassen modelliert und testweise hochgeladen auf <https://www.snik.eu/ontology/bb/ItService>.
Falls das tatsächlich mit Instanzen modelliert oder etwas anderes geändert werden soll, dann diese Issue bitte wieder öffnen.
