### ISSUE TITLE
http://www.snik.eu/ontology/ob/Tender

### ISSUE THREAD

**Issue by AlfredWinter** [snikproject/ontology#479]
Problem with the class [ob:Tender](http://www.snik.eu/ontology/ob/Tender) ([OntoWiki URL](https://www.snik.eu/ontowiki/view/?r=http://www.snik.eu/ontology/ob/Tender&m=http://www.snik.eu/ontology/ob)):

Hier haben wir einen Widerspruch: Hier steht Tender für Ausschreibung, bei http://www.snik.eu/ontology/he/Angebot ist aber "Tender" ein Angebot und damit closeMatch zu "Bid"

Klären, was in den jeweiliegen Quellen wirklich gemeint ist und dann auch noch mal Englische Übersetzung prüfen.

**Comment by KonradHoeffner** [comment]
ob:Tender steht definitiv für eine Ausschreibung, das wird auch in der Definition so beschrieben.
he:Tender hat bereits ein close match zu ob:Bid, damit stimmt das also.

Das Problem ist also das englische Label von he:Angebot, ich ändere das um in "Bid".
