### ISSUE TITLE
http://www.snik.eu/ontology/ob/InformationManagementEntityType v0.3.0, 2016-11-18

### ISSUE THREAD

**Issue by AlfredWinter** [snikproject/ontology#54]
The class http://www.snik.eu/ontology/ob/InformationManagementEntityType has [incorrect/missing attribute values | incorrect/missing relations to other classes, other (please specify and remove not applicable ones).]

**Details**
Der Name mit der 1 am Schluss und die Anzeige eines Errors in der description deuten darauf, dass hier noch bearbeitet werden muss. Frau Jahn möge sich den Begriff anschauen.

**Comment by KonradHoeffner** [comment]
Die Ressource gibt es nicht mehr, das Problem hat sich damit anscheinend erledigt.
