### ISSUE TITLE
http://www.snik.eu/ontology/bb/AnnualITBudget v0.3.0, 2016-11-18

### ISSUE THREAD

**Issue by AlfredWinter** [snikproject/ontology#69]
The class http://www.snik.eu/ontology/bb/AnnualITBudget has [incorrect/missing attribute values | incorrect/missing relations to other classes, other (please specify and remove not applicable ones).]

**Details**
nachtragen: Relation : Budget has component Annual It-Budget

**Comment by KonradHoeffner** [comment]
Die Klasse Budget existiert nur im Heinrich. Wie soll ich vorgehen: (1) Die Klasse bb:Budget erzeugen, (2) Die Klasse he:Budget verwenden, (3) Andere Lösung?

**Comment by FranziskaJahn** [comment]
Hatten wir bei den Interontologie-Beziehungen auch "broader" und "narrower" zur Verfügung? Dann würde ich diese verwenden. Falls nicht, so belassen wie es ist.

**Comment by KonradHoeffner** [comment]
Ja, skos:narrowMatch und skos:broadMatch. Allerdings ersetzen die nur rdfs:subClassOf, nicht andere Relationen wie meta:entityTypeComponent.

Siehe auch https://wiki.imise.uni-leipzig.de/Projekte/SNIK/ontologie/extraktion/relationen

**Comment by AlfredWinter** [comment]
(IT-)Budget in bb suchen, ggf. ergänzen; sonst closeMatch

**Comment by KonradHoeffner** [comment]
Im blauen Buch gibt es [bb:HisBudgetPlanning](https://www.snik.eu/ontology/bb/HisBudgetPlanning) und [bb:HospitalBudget](https://www.snik.eu/ontology/bb/HospitalBudget). Welches soll wie verknüpft werden?

**Comment by AlfredWinter** [comment]
bb/AnnualITBudget isSubClassOf bb:HospitalBudget.
bb:HisBudgetPlanning updates bb/AnnualITBudget
