### ISSUE TITLE
http://www.snik.eu/ontology/bb/Certification v0.3.3, 2017-04-18

### ISSUE THREAD

**Issue by AlfredWinter** [snikproject/ontology#96]
The class http://www.snik.eu/ontology/bb/Certification has [incorrect/missing attribute values | incorrect/missing relations to other classes, other (please specify and remove not applicable ones).]

**Details**
Begriff hat keine Beziehung zu einem anderen Begriff aus dem bb. das ist von einem Domänenexperten zu korrigieren.

**Comment by AnnaLoerke** [comment]
Aktuell sind CertificationByCCHIT/CertificationByEurorec/CertificationByISO subclassOf HisCertification. Wäre es dann von der Hierarchie und um Doppelungen zu vermeiden sinnvoll diese drei nicht direkt mit Certification zu verbinden, sondern die Vererbung als ausreichend zu betrachten und nur HisCertification als subclassOf Certification zu modellieren?

Bezüglich InpatientEHRCertification und OutpatientEHRCertification versuche ich mal ein Screenshot anzuhängen, damit wir entscheiden können, ob uns die bisherige Struktur reicht oder wir tatsächlich dort subclassOf modellieren wollen.
<img width="593" alt="bildschirmfoto 2019-01-25 um 10 51 01" src="https://user-images.githubusercontent.com/36420864/51738340-3dc14800-208f-11e9-9993-e80694dca636.png">

**Comment by AlfredWinter** [comment]
erscheint mir plausibel

**Comment by KonradHoeffner** [comment]
@FranziskaJahn: Wie ist da jetzt die endgültige Liste der hinzuzufügenden Statements?

**Comment by KonradHoeffner** [comment]
Modifizierte Änderung nach Annas Anmerkung:

HisCertification subclassOf Certification
